#!/bin/bash

cpu_usage(){
 CPU=$(top -bn1 | grep "Cpu(s):" | \
	sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
	awk '{print 100 - $1"%"}')
	echo "CPU Usage: $CPU"
}


display(){
echo "===> System Monitor <==="
cpu_usage
}

while true; do
	clear	
	display
	sleep 2
	done
